// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6cyq_VAl7egMEShFxOAbRS9N7sNMlX1Y',
    appId: '1:482520108781:web:23b40277b88933b5eb06e4',
    messagingSenderId: '482520108781',
    projectId: 'marketa-6ad4c',
    authDomain: 'marketa-6ad4c.firebaseapp.com',
    storageBucket: 'marketa-6ad4c.firebasestorage.app',
    measurementId: 'G-NM76DG650W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgoG3oN46dKlT4k2fxxOceiDr2LclmBtQ',
    appId: '1:482520108781:android:1b851cc3f3c04c9feb06e4',
    messagingSenderId: '482520108781',
    projectId: 'marketa-6ad4c',
    storageBucket: 'marketa-6ad4c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC1leao4G_VCpJJi-acpPj5SRvB8sQFp0',
    appId: '1:482520108781:ios:b368d36b3da2b33beb06e4',
    messagingSenderId: '482520108781',
    projectId: 'marketa-6ad4c',
    storageBucket: 'marketa-6ad4c.firebasestorage.app',
    iosBundleId: 'com.example.marketa',
  );
}
